// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations.PerfilFinancieroDb
{
    [DbContext(typeof(PerfilFinancieroDbContext))]
    [Migration("20260506023931_AgregarPerfilFinanciero")]
    partial class AgregarPerfilFinanciero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.PerfilFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Control")
                        .HasColumnType("int");

                    b.Property<int>("Estabilidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<int>("Planificacion")
                        .HasColumnType("int");

                    b.Property<int>("TendEgresos")
                        .HasColumnType("int");

                    b.Property<int>("TendIngresos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PerfilesFinancieros");
                });
#pragma warning restore 612, 618
        }
    }
}
